In [80]:
import numpy as np

In [81]:
#Q1. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
def fun1():
    a1=np.array([1,7,13,105])
    print(a1)
    print(a1.itemsize)
    print(a1.nbytes)




In [82]:
fun1()

[  1   7  13 105]
8
32


In [83]:
#Q2.Write a NumPy program to create an element-wise comparison (greater,greater_equal, less and less_equal) of two given arrays.

def fun2(a):
    a1=[11,22,33,44]
    a2=[55,66,77,88]
   
    if a2[a]>a1[a]:
        print("a2 is greater")
    elif a1[a]==a2[a]:
        print("a1 and a2 are equal")
    elif a1[a]<a2[a]:
        print("a1 is smaller")
    elif a1[a]<=a2[a]:
        print("a1 is smaller or equal to a2")

fun2(3)



a2 is greater


In [90]:
#Q3.Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives, 10 tens, 10 twentys and 10 fiftys.
def fun3():  
    a1=np.zeros(10)
    a2=np.ones(10)
    print(a1)
    print(a2)
    print(a2*5)
    print(a2*20)
    print(a2*50)


In [85]:
fun3()

[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [86]:
#Q4. Write a NumPy program to create an array of integers from 30 to 70.
def fun4():
    arr=np.arange(30,70)
    print(arr)


fun4()

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [87]:
#q5. Write a NumPy program to create an array of integers from 50 to 95.
def fun():
    arr=np.arange(50,95)
    print(arr)


fun()

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [89]:
#Q6. Write a NumPy program to create an array of all even integers from 20 to 80.
def fun():
    arr=np.arange(20,80,2)
    print(arr)


fun()



[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [92]:
#Q7. Write a NumPy program to create an array of all odd integers from 20 to 80.
def fun():
    arr=np.arange(19,80,2)
    print(arr)


fun()

[19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65
 67 69 71 73 75 77 79]


In [93]:
 #Q8. Write a NumPy program to generate an array of 15 random numbers from 10 to 40.
def fun():
    arr=np.random.randint(10,40,15)
    print(arr)
fun()



[34 12 34 29 35 10 12 25 11 24 16 11 39 27 26]


In [95]:
#Q9. Write a NumPy program to generate an array of 10 random numbers from 30 to 50.
def fun():
    arr=np.random.randint(30,50,10)
    print(arr)
fun()

    

[39 37 43 39 31 46 38 49 30 32]


In [96]:
#Q10. Write a NumPy program to generate an array of 20 random numbers from 50 to 90.
def fun():
    arr=np.random.randint(50,90,20)
    print(arr)
fun()


[59 83 58 53 78 73 63 58 75 50 54 66 88 87 51 58 73 70 77 72]


In [97]:
# Q11.Create any two arrays & perform various mathematical operations.
#     i.e. Addition, Substraction, Multiplication, Divide.
n1 = np.array([11,22,33,44])
n2 = np.array([10,20,30,40])
print(f"N1 = {n1}")
print(f"N2 = {n2}")
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)

N1 = [11 22 33 44]
N2 = [10 20 30 40]
[21 42 63 84]
[1 2 3 4]
[ 110  440  990 1760]
[1.1 1.1 1.1 1.1]


In [137]:
#Q12.Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

def fun():
    arr=np.arange(10,22).reshape((3,4))
    print(arr)
fun()

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [114]:
#Q13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.
def fun():
    arr=np.array([1,0,0,0,1,0,0,0,1])
    
    arr=arr.reshape([3,3])
    print(arr)


fun()
    






[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [110]:
#Q14. Write a NumPy program to find the number of rows and columns in a given matrix. 
def fun():
    arr=np.random.randint(30,50,9)
    print(arr)
    arr = arr.reshape([3,3])
    print(arr)
    print(f"Shape = {arr.shape}")


fun()




Shape = (3, 3)


In [112]:
#Q15. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.


a=np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [117]:
#Q16. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
x=np.random.random([3,3,3])
print(x)

[[[0.18480008 0.6212091  0.97841245]
  [0.08384052 0.50406524 0.61715582]
  [0.03190451 0.54979741 0.42968965]]

 [[0.56747303 0.0224581  0.86382826]
  [0.91816499 0.76261584 0.70659269]
  [0.35886078 0.38584214 0.36004762]]

 [[0.73911634 0.38048587 0.91975688]
  [0.47367016 0.97382345 0.87190901]
  [0.65442288 0.49093264 0.27604723]]]


In [118]:
#Q17. Write a NumPy program to create a 2x3x4 array filled with arbitrary values.

x=np.random.random([2,3,4])
print(x)


[[[0.3438884  0.48930178 0.73694376 0.87772276]
  [0.9077742  0.40832336 0.89989965 0.92477509]
  [0.23348292 0.49834279 0.34710254 0.28472369]]

 [[0.44254395 0.72474153 0.77460907 0.98787619]
  [0.8984225  0.22676434 0.8549512  0.54016058]
  [0.76760407 0.54952137 0.98950249 0.97470891]]]


In [120]:
#Q18. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
l1=[1,2,3,4,5,6]
print(l1)
arr=np.array(l1)
print(arr)




[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [127]:
#Q19. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

def fun():
    arr=np.arange(2,11).reshape(3,3)
    print(arr)
fun()

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [135]:
#Q20. Write a NumPy program to create an array with values ranging from 12 to 38.
arr=np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [147]:
#Q21. Write a NumPy program to reverse an array (the first element becomes the last).
arr=np.array([1,2,3,4,6,7,8,9])
print(arr)
arr=arr[::-1]
print(arr)

[1 2 3 4 6 7 8 9]
[9 8 7 6 4 3 2 1]


In [150]:
#Q22. Write a NumPy program to convert an data type into to a floating type.
arr=[12,34,123,421,43,23]
print(arr)
x = np.asfarray(arr)
print(x)


[12, 34, 123, 421, 43, 23]
[ 12.  34. 123. 421.  43.  23.]


In [151]:
#Q23. Write a NumPy program to convert a list array.
l1=[[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]]
print(l1)
arr=np.array(l1)
print(arr)



[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [11, 22, 33, 44, 55]]
[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]


In [156]:
#Q24. Write a NumPy program to get the element-wise remainder of an array of division.
arr=np.arange(1,50)
print(arr)
print(np.remainder(arr,3))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
[1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1
 2 0 1 2 0 1 2 0 1 2 0 1]


In [155]:
#Q25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.
arr=np.arange(20,50)
print(arr)
print(np.remainder(arr,3))


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
